### ISSUE TITLE
Rename to BLASBenchmarksCPU.jl and register in the General registry?

### ISSUE THREAD

**Issue by DilumAluthge** [chriselrod/BLASBenchmarksCPU.jl#20]
Once StrideArrays.jl is registered, what do you think about registering this package as well? That way, the process for a user to run benchmarks becomes really really easy:

```
using Pkg
Pkg.add("BLASBenchmarksCPU")
using BLASBenchmarksCPU
result = runbench()
plot(result)
```

Then, we can advertise this on Discourse, Slack, etc. and we can try to get a bunch of different people to run the benchmarks, which will give us a better idea of how Octavian performs on multiple different machines.

Before registering though, I was thinking about renaming the package. I was trying to figure out whether GPU BLAS benchmarking would go into this package or a different package. Looking at some examples (e.g. https://github.com/JuliaGPU/GemmKernels.jl/tree/master/benchmarks/wmma), it looks like the workflow for benchmarking on CUDA devices is different enough from the CPU workflow (e.g. you have to use the NVIDIA profiler). So I'm thinking it makes the most sense to have the GPU benchmarking in a different package.

I was thinking that we could rename this package to BLASBenchmarksCPU.jl or something like that.

And then I'm planning on creating a separate package BLASBenchmarksGPU.jl or maybe BLASBenchmarksCUDA.jl.

How does that sound?

**Comment by chriselrod** [comment]
BLASBenchmarksCPU or CPUBLASBenchmarks? I guess the latter mashes together two acronyms, which is a bit much.

I removed all references to `StrideArrays.jl`, so we don't need to wait.

**Comment by DilumAluthge** [comment]
Yeah I figured the juxtaposition `CPUBLAS' was a little unreadable.

**Comment by chriselrod** [comment]
Okay, I've renamed it.

**Comment by DilumAluthge** [comment]
Good to register now?

**Comment by DilumAluthge** [comment]
Fixed by https://github.com/JuliaRegistries/General/pull/28482, which will be auto-merged in 3 days.
