### ISSUE TITLE
Bind benchmark libraries to fixed, standard colors in plots

### ISSUE THREAD

**Issue by stillyslalom** [chriselrod/BLASBenchmarksCPU.jl#28]
Easier to compare from run to run, or between different folks' benchmarks, if MKL is always red, OpenBLAS is always black, etc.

**Comment by chriselrod** [comment]
I would also like it to now always set the limits at an integer `log10` value. That creates unnecessary and excessive amounts of whitespace much of the time.

**Comment by mcabbott** [comment]
You could consider also doing Julia = solid, C call = dashed, or some code like that.
