### ISSUE TITLE
Customize the colors used in the plot?

### ISSUE THREAD

**Issue by DilumAluthge** [chriselrod/BLASBenchmarksCPU.jl#8]
Is there a way to provide a list of colors for the plot? By default, it picks some greens and blues that look pretty similar.

**Comment by chriselrod** [comment]
From [here](https://www.queryverse.org/VegaLite.jl/stable/examples/examples_histograms/#Stacked-Density-Estimates-1):
```julia
@vlplot(
    width=400,
    height=100,
    :area,
    transform=[
        {density="IMDB_Rating",bandwidth=0.3,groupby=["Major_Genre"],extent=[0, 10],counts=true,steps=50}
    ],
    x={"value:q", title="IMDB Rating"},
    y= {"density:q",stack=true},
    color={"Major_Genre:n",scale={scheme=:category20}}
)
```
we can specify `color={scale={scheme=:category20}}`.
[Here](https://vega.github.io/vega-lite-v1/docs/scale.html#color-palette) is a list of the build in options in place of `category20`. There don't seem to be many.

**Comment by DilumAluthge** [comment]
> You could also change the plotting library.

Yeah I think this is probably the most robust approach.
